export enum BookingStatus {
  DRAFT = 'DRAFT',
  SEATS_LOCKED = 'SEATS_LOCKED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  EXPIRED = 'EXPIRED',
}
